export type MacroOp = "replace" | "uppercase" | "lowercase" | "trim" | "prefix" | "suffix";

export type ColumnStat = {
  name: string;
  nonEmpty: number;
  distinct: number;
  inferred: string;
};

export type FullColumnStat = {
  name: string;
  non_empty: number;
  distinct: number;
  distinct_truncated: boolean;
  inferred: string;
};

export type SortRule = { column: string; direction: "asc" | "desc" };
export type FilterRule = { column: string; value: string };

export type PanelsProps = {
  showMacroPanel: boolean;
  showOpsPanel: boolean;
  showExportPanel: boolean;
  showFindPanel: boolean;
  showStatsPanel: boolean;
  macroOp: MacroOp;
  macroColumn: string;
  macroFind: string;
  macroReplace: string;
  macroText: string;
  macroOutputPath: string | null;
  onMacroOpChange: (value: MacroOp) => void;
  onMacroColumnChange: (value: string) => void;
  onMacroFindChange: (value: string) => void;
  onMacroReplaceChange: (value: string) => void;
  onMacroTextChange: (value: string) => void;
  onRunMacro: () => void;
  onRunMacroOnFile: () => void;
  rowIndexInput: string;
  columnIndexInput: string;
  columnNameInput: string;
  onRowIndexChange: (value: string) => void;
  onColumnIndexChange: (value: string) => void;
  onColumnNameChange: (value: string) => void;
  onInsertRow: () => void;
  onDeleteRow: () => void;
  onCopySelection: () => void;
  onPasteSelection: () => void;
  onInsertColumn: () => void;
  onDeleteColumn: () => void;
  onRenameColumn: () => void;
  sortColumnInput: string;
  sortDirection: "asc" | "desc";
  filterColumnInput: string;
  filterText: string;
  onSortColumnChange: (value: string) => void;
  onSortDirectionChange: (value: "asc" | "desc") => void;
  onFilterColumnChange: (value: string) => void;
  onFilterTextChange: (value: string) => void;
  onAddSortRule: () => void;
  onAddFilterRule: () => void;
  onClearSortFilter: () => void;
  sortRules: SortRule[];
  filterRules: FilterRule[];
  onRemoveSortRule: (index: number) => void;
  onRemoveFilterRule: (index: number) => void;
  encodingMode: "UTF-8" | "UTF-16LE";
  eolMode: "CRLF" | "LF";
  includeBom: boolean;
  dialectDelimiter: string;
  dialectQuote: string;
  dialectEscape: string;
  onEncodingModeChange: (value: "UTF-8" | "UTF-16LE") => void;
  onEolModeChange: (value: "CRLF" | "LF") => void;
  onIncludeBomChange: (value: boolean) => void;
  onDialectDelimiterChange: (value: string) => void;
  onDialectQuoteChange: (value: string) => void;
  onDialectEscapeChange: (value: string) => void;
  findText: string;
  replaceText: string;
  findColumnInput: string;
  findStartRow: string;
  findEndRow: string;
  useRegex: boolean;
  matchCase: boolean;
  findOutputPath: string | null;
  onFindTextChange: (value: string) => void;
  onReplaceTextChange: (value: string) => void;
  onFindColumnChange: (value: string) => void;
  onFindStartRowChange: (value: string) => void;
  onFindEndRowChange: (value: string) => void;
  onUseRegexChange: (value: boolean) => void;
  onMatchCaseChange: (value: boolean) => void;
  onApplyFindReplace: () => void;
  onApplyFindReplaceOnFile: () => void;
  columnStats: ColumnStat[];
  fullStats: FullColumnStat[] | null;
  fullStatsLoading: boolean;
  onRunFullStats: () => void;
  loading: boolean;
  hasPreview: boolean;
  t: (en: string, zh: string) => string;
};
