export type MacroOp = "replace" | "uppercase" | "lowercase" | "trim" | "prefix" | "suffix";

export type ColumnStat = {
  name: string;
  nonEmpty: number;
  distinct: number;
  inferred: string;
};

export type FullColumnStat = {
  name: string;
  non_empty: number;
  distinct: number;
  distinct_truncated: boolean;
  inferred: string;
};

export type SortRule = { column: string; direction: "asc" | "desc" };
export type FilterRule = { column: string; value: string };

export type PanelsProps = {
  showMacroPanel: boolean;
  showOpsPanel: boolean;
  showExportPanel: boolean;
  showFindPanel: boolean;
  showStatsPanel: boolean;
  macroOp: MacroOp;
  macroColumn: string;
  macroFind: string;
  macroReplace: string;
  macroText: string;
  macroScope: "loaded" | "file";
  macroOutputPath: string | null;
  onMacroOpChange: (value: MacroOp) => void;
  onMacroColumnChange: (value: string) => void;
  onMacroFindChange: (value: string) => void;
  onMacroReplaceChange: (value: string) => void;
  onMacroTextChange: (value: string) => void;
  onMacroScopeChange: (value: "loaded" | "file") => void;
  onRunMacro: () => void;
  rowIndexInput: string;
  columnIndexInput: string;
  columnNameInput: string;
  onRowIndexChange: (value: string) => void;
  onColumnIndexChange: (value: string) => void;
  onColumnNameChange: (value: string) => void;
  onInsertRow: () => void;
  onDeleteRow: () => void;
  onCopySelection: () => void;
  onPasteSelection: () => void;
  pasteMode: "auto" | "strict" | "delimiter";
  onPasteModeChange: (value: "auto" | "strict" | "delimiter") => void;
  columnSearch: string;
  onColumnSearchChange: (value: string) => void;
  hiddenCols: number[];
  onToggleColumnHidden: (index: number) => void;
  onShowAllColumns: () => void;
  onHideAllColumns: () => void;
  onMoveColumnUp: (index: number) => void;
  onMoveColumnDown: (index: number) => void;
  importSkipRows: string;
  onImportSkipRowsChange: (value: string) => void;
  importFirstRowHeader: boolean;
  onImportFirstRowHeaderChange: (value: boolean) => void;
  onInsertColumn: () => void;
  onDeleteColumn: () => void;
  onRenameColumn: () => void;
  sortColumnInput: string;
  sortDirection: "asc" | "desc";
  filterColumnInput: string;
  filterText: string;
  onSortColumnChange: (value: string) => void;
  onSortDirectionChange: (value: "asc" | "desc") => void;
  onFilterColumnChange: (value: string) => void;
  onFilterTextChange: (value: string) => void;
  onAddSortRule: () => void;
  onAddFilterRule: () => void;
  onClearSortFilter: () => void;
  sortRules: SortRule[];
  filterRules: FilterRule[];
  onRemoveSortRule: (index: number) => void;
  onRemoveFilterRule: (index: number) => void;
  encodingMode: "UTF-8" | "UTF-16LE";
  eolMode: "CRLF" | "LF";
  includeBom: boolean;
  dialectDelimiter: string;
  dialectQuote: string;
  dialectEscape: string;
  onEncodingModeChange: (value: "UTF-8" | "UTF-16LE") => void;
  onEolModeChange: (value: "CRLF" | "LF") => void;
  onIncludeBomChange: (value: boolean) => void;
  onDialectDelimiterChange: (value: string) => void;
  onDialectQuoteChange: (value: string) => void;
  onDialectEscapeChange: (value: string) => void;
  findText: string;
  replaceText: string;
  findScope: "loaded" | "file";
  findColumnInput: string;
  findStartRow: string;
  findEndRow: string;
  useRegex: boolean;
  matchCase: boolean;
  findOutputPath: string | null;
  findMatches: Array<{ row: number; col: number; value: string }>;
  activeFindMatchIndex: number;
  findMatchesSource: "loaded" | "file" | "view";
  findMatchesHasMore: boolean;
  findRunning: boolean;
  findProgress: number;
  findCanceled: boolean;
  findMatchedCount: number | null;
  findScannedRows: number | null;
  findElapsedMs: number | null;
  onFindTextChange: (value: string) => void;
  onReplaceTextChange: (value: string) => void;
  onFindScopeChange: (value: "loaded" | "file") => void;
  onFindColumnChange: (value: string) => void;
  onFindStartRowChange: (value: string) => void;
  onFindEndRowChange: (value: string) => void;
  onUseRegexChange: (value: boolean) => void;
  onMatchCaseChange: (value: boolean) => void;
  onFindMatches: () => void;
  onFindPrev: () => void;
  onFindNext: () => void;
  onFindClear: () => void;
  onFindCancel: () => void;
  onFindJump: (index: number) => void;
  onApplyFindReplace: () => void;
  columnStats: ColumnStat[];
  fullStats: FullColumnStat[] | null;
  fullStatsLoading: boolean;
  onRunFullStats: () => void;
  loading: boolean;
  sortFilterActive: boolean;
  sortFilterMemoryLimitMb: number;
  sortFilterMemoryLimitText: string;
  onSortFilterMemoryLimitTextChange: (value: string) => void;
  onSortFilterMemoryLimitCommit: (value: number) => void;
  forceExternalSort: boolean;
  onForceExternalSortChange: (value: boolean) => void;
  autoIndexMode: "large_only" | "all";
  onAutoIndexModeChange: (value: "large_only" | "all") => void;
  columnSelectOptions: Array<{ value: string; label: string }>;
  hasPreview: boolean;
  t: (en: string, zh: string) => string;
};
