import type { ReactNode, RefObject } from "react";

export type TextModeWorkspaceProps = {
  t: (en: string, zh: string) => string;
  textPath: string | null;
  textDirty: boolean;
  textEncoding: "UTF-8" | "UTF-16LE";
  textReadOnlyPreview: boolean;
  textLoading: boolean;
  textReplaceRunning: boolean;
  textPreviewHasPrev: boolean;
  textPreviewHasNext: boolean;
  textChunkJumpInput: string;
  textTotalBytes: number | null;
  textFindQuery: string;
  textFindRunning: boolean;
  textReplaceValue: string;
  textReplacePreserveCase: boolean;
  textReplaceConfirmEach: boolean;
  textReplaceHasPendingConfirm: boolean;
  textFindUseRegex: boolean;
  textFindMatchCase: boolean;
  textFindHitsLength: number;
  textPreviewOffset: number;
  textPreviewBytes: number | null;
  largeTextPreviewBytes: number;
  largeTextFileThresholdBytes: number;
  textReplaceProgress: number;
  textReplaceAppliedCount: number | null;
  textReplaceElapsedMs: number | null;
  textFindProgress: number;
  textFindMatchedCount: number | null;
  textFindHasMore: boolean;
  activeTextFindIndex: number;
  textContent: string;
  error: string | null;
  textAreaRef: RefObject<HTMLTextAreaElement | null>;
  findResultsPanel: ReactNode;
  formatByteSize: (bytes: number | null) => string;
  setTextEncoding: (value: "UTF-8" | "UTF-16LE") => void;
  setTextChunkJumpInput: (value: string) => void;
  setTextFindQuery: (value: string) => void;
  setTextReplaceValue: (value: string) => void;
  setTextReplacePreserveCase: (value: boolean) => void;
  setTextReplaceConfirmEach: (value: boolean) => void;
  setTextFindUseRegex: (value: boolean) => void;
  setTextFindMatchCase: (value: boolean) => void;
  setTextContent: (value: string) => void;
  saveCurrent: () => boolean | void | Promise<boolean | void>;
  saveTextAs: () => boolean | void | Promise<boolean | void>;
  loadPrevTextPreviewChunk: () => boolean | void | Promise<boolean | void>;
  loadNextTextPreviewChunk: () => boolean | void | Promise<boolean | void>;
  jumpToTextChunk: () => boolean | void | Promise<boolean | void>;
  runTextFind: () => void | Promise<void>;
  runTextReplaceInChunk: (replaceAll: boolean) => void;
  runTextReplaceNext: () => void;
  runTextReplaceConfirmNext: () => void;
  runTextReplaceInSelection: (replaceAll: boolean) => void;
  runTextReplaceInFile: () => void | Promise<void>;
  jumpTextFindPrev: () => void;
  jumpTextFindNext: () => void;
  cancelTextReplaceJobInternal: (showMessage: boolean) => void | Promise<void>;
  cancelTextFindJobInternal: (showMessage: boolean) => void | Promise<void>;
};
