export type StatusBarProps = {
  loading: boolean;
  loadingRows: boolean;
  hasPreview: boolean;
  eof: boolean;
  rowsLength: number;
  visibleCount: number;
  patchCount: number;
  macroAppliedCount: number;
  findAppliedCount: number;
  opStatus: string | null;
  indexing: boolean;
  indexProgress: number;
  indexCanceled: boolean;
  globalViewLoading: boolean;
  onCancelIndex?: () => void;
  onBuildIndex?: () => void;
  canBuildIndex?: boolean;
  t: (en: string, zh: string) => string;
};
