import { buildCsvEditorPageProps } from "../pages/CsvEditorPage/buildProps";
import { buildCsvWorkspacePageProps } from "../pages/CsvWorkspacePage/buildProps";
import { buildTextEditorPageProps } from "../pages/TextEditorPage/buildProps";

type BuildAppViewPagePropsContext = Record<string, any>;

export default function buildAppViewPageProps(ctx: BuildAppViewPagePropsContext) {
  const csvEditorPageProps = buildCsvEditorPageProps({
    ...ctx.csvInputState,
    ...ctx.csvSortFilterModel,
    ...ctx.csvPanelVisibilityState,
    ...ctx.sortFilterPreferences,
    ...ctx.localeState,
    ...ctx.csvFindState,
    ...ctx.diagnosticsState,
    ...ctx.fileOpsState,
    ...ctx.csvViewOrchestration,
    ...ctx.csvWorkflowActions,
    ...ctx.appCommandActions,
    activeFindMatchIndex: ctx.activeFindMatchIndex,
    activeRange: ctx.activeRange,
    activeTabId: ctx.activeTabId,
    autoFitColumns: ctx.autoFitColumns,
    cancelEditing: ctx.cancelEditing,
    cancelHeaderEditing: ctx.cancelHeaderEditing,
    clearSelection: ctx.clearSelection,
    columnWidths: ctx.columnWidths,
    commitEditing: ctx.commitEditing,
    commitHeaderEditing: ctx.commitHeaderEditing,
    delimiter: ctx.delimiter,
    delimiterApplied: ctx.delimiterApplied,
    delimiterPresets: ctx.delimiterPresets,
    drawerCollapsed: ctx.drawerCollapsed,
    editingCell: ctx.editingCell,
    editingHeader: ctx.editingHeader,
    error: ctx.error,
    freezeFirstCol: ctx.freezeFirstCol,
    freezeFirstRow: ctx.freezeFirstRow,
    getCellValue: ctx.getCellValue,
    globalViewLoading: ctx.globalViewLoading,
    gridHeaders: ctx.gridHeaders,
    gridTemplateColumns: ctx.gridTemplateColumns,
    handleHideAllColumns: ctx.handleHideAllColumns,
    handleShowAllColumns: ctx.handleShowAllColumns,
    handleToggleColumnHidden: ctx.handleToggleColumnHidden,
    handleNewTab: ctx.appCommandActions.handleOpen,
    hasSortFilter: ctx.hasSortFilter,
    headerHeightOverride: ctx.headerHeightOverride,
    hiddenCols: ctx.hiddenCols,
    isCellInSelection: ctx.isCellInSelection,
    isColInSelection: ctx.isColInSelection,
    isDraggingSelection: ctx.isDraggingSelection,
    isRowInSelection: ctx.isRowInSelection,
    loading: ctx.loading,
    pasteSelection: ctx.pasteSelection,
    patches: ctx.patches,
    preview: ctx.preview,
    recentFiles: ctx.recentFiles,
    redo: ctx.redo,
    redoStack: ctx.redoStack,
    rowHeaderWidth: ctx.rowHeaderWidth,
    rowHeight: ctx.rowHeight,
    rows: ctx.rows,
    selectionAnchor: ctx.selectionAnchor,
    selectionColumnCount: ctx.selectionColumnCount,
    selectionMode: ctx.selectionMode,
    setAutoFitColumns: ctx.setAutoFitColumns,
    setCsvGridFocused: ctx.setCsvGridFocused,
    setDelimiter: ctx.setDelimiter,
    setDrawerCollapsed: ctx.setDrawerCollapsed,
    setEditingCell: ctx.setEditingCell,
    setEditingHeader: ctx.setEditingHeader,
    setFreezeFirstCol: ctx.setFreezeFirstCol,
    setFreezeFirstRow: ctx.setFreezeFirstRow,
    setIsDraggingSelection: ctx.setIsDraggingSelection,
    showDrawer: ctx.showDrawer,
    showPanels: ctx.showPanels,
    sidebarWidth: ctx.sidebarWidth,
    startColumnResize: ctx.startColumnResize,
    startColumnResizeAll: ctx.startColumnResizeAll,
    startEditing: ctx.startEditing,
    startHeaderEditing: ctx.startHeaderEditing,
    startHeaderRowHeightResize: ctx.startHeaderRowHeightResize,
    startRowHeaderResize: ctx.startRowHeaderResize,
    startRowHeightResizeAll: ctx.startRowHeightResizeAll,
    startRowHeightResizeRow: ctx.startRowHeightResizeRow,
    startSidebarResize: ctx.startSidebarResize,
    t: ctx.t,
    tabs: ctx.tabs,
    undo: ctx.undo,
    undoStack: ctx.undoStack,
    updateSelection: ctx.updateSelection,
  });

  const textEditorPageProps = buildTextEditorPageProps({
    ...ctx.textFindReplaceState,
    ...ctx.textFindResultPanelPagination,
    ...ctx.textFindResultsModelState,
    ...ctx.textSearchActions,
    t: ctx.t,
    textPath: ctx.textPath,
    textDirty: ctx.textDirty,
    textEncoding: ctx.textEncoding,
    textReadOnlyPreview: ctx.textReadOnlyPreview,
    textLoading: ctx.textLoading,
    textPreviewHasPrev: ctx.textPreviewHasPrev,
    textPreviewHasNext: ctx.textPreviewHasNext,
    textTotalBytes: ctx.textTotalBytes,
    textPreviewOffset: ctx.textPreviewOffset,
    textPreviewBytes: ctx.textPreviewBytes,
    largeTextPreviewBytes: ctx.largeTextPreviewBytes,
    largeTextFileThresholdBytes: ctx.largeTextFileThresholdBytes,
    textContent: ctx.textContent,
    error: ctx.error,
    formatByteSize: ctx.formatByteSize,
    setTextEncoding: ctx.setTextEncoding,
    setTextContent: ctx.setTextContent,
    saveCurrent: ctx.appCommandActions.saveCurrent,
    loadPrevTextPreviewChunk: ctx.loadPrevTextPreviewChunk,
    loadNextTextPreviewChunk: ctx.loadNextTextPreviewChunk,
  });

  const csvWorkspacePageProps = buildCsvWorkspacePageProps({
    csvEditorPageProps,
    t: ctx.t,
    loading: ctx.loading,
    windowLoading: ctx.windowLoading,
    fileMode: ctx.fileMode,
    csvGridFocused: ctx.csvGridFocused,
    editingCell: ctx.editingCell,
    selectionMode: ctx.selectionMode,
    previewPath: ctx.previewPath,
    eof: ctx.eof,
    rowsLength: ctx.rowsLength,
    patchCount: ctx.patchCount,
    macroAppliedCount: ctx.fileOpsState.macroAppliedCount,
    findAppliedCount: ctx.fileOpsState.findAppliedCount,
    opStatus: ctx.fileOpsState.opStatus,
    indexRunning: ctx.indexRunning,
    indexProgress: ctx.indexProgress,
    indexCanceled: ctx.indexCanceled,
    findRunning: ctx.csvWorkflowActions.findRunning,
    findProgress: ctx.csvWorkflowActions.findProgress,
    findCanceled: ctx.csvWorkflowActions.findCanceled,
    findMatchedCount: ctx.csvWorkflowActions.findMatchedCount,
    findScannedRows: ctx.csvWorkflowActions.findScannedRows,
    findElapsedMs: ctx.csvWorkflowActions.findElapsedMs,
    globalViewLoading: ctx.globalViewLoading,
    autoIndexMode: ctx.autoIndexMode,
    forceExternalSort: ctx.forceExternalSort,
    lastIndexTrigger: ctx.lastIndexTrigger,
    totalRows: ctx.totalRows,
    delimiter: ctx.delimiter,
    delimiterApplied: ctx.delimiterApplied,
    refreshTotalRows: ctx.refreshTotalRows,
    cancelIndexBuild: ctx.cancelIndexBuild,
    cancelFindMatchJob: ctx.csvWorkflowActions.cancelFindMatchJob,
    contextMenu: ctx.csvWorkflowActions.contextMenu,
    onRunContextAction: (action: string) => {
      void ctx.csvWorkflowActions.runContextAction(action);
    },
  });

  return {
    csvEditorPageProps,
    textEditorPageProps,
    csvWorkspacePageProps,
  };
}
