import type { UseTabAndFileActionsOptions } from "./useTabAndFileActions";

type BuildTabAndFileActionOptionsContext = Record<string, any>;

export default function buildTabAndFileActionOptions(
  ctx: BuildTabAndFileActionOptionsContext,
): UseTabAndFileActionsOptions {
  return {
    saveCurrentArgs: {
      fileMode: ctx.fileMode,
      textPath: ctx.textPath,
      saveTextTo: ctx.saveTextTo,
      saveTextAs: ctx.saveTextAs,
      previewPath: ctx.previewPath,
      saveToPath: ctx.saveToPath,
      clearDraftForPath: ctx.clearDraftForPath,
      setPatches: ctx.setPatches,
      setUndoStack: ctx.setUndoStack,
      setRedoStack: ctx.setRedoStack,
      resetOps: ctx.resetOps,
      resetFileOps: ctx.resetFileOps,
      setClearedRows: ctx.setClearedRows,
      setClearedCols: ctx.setClearedCols,
      setEditingCell: ctx.setEditingCell,
      requestWindow: ctx.requestWindow,
      windowStart: ctx.windowStart,
      delimiterApplied: ctx.delimiterApplied,
      delimiter: ctx.delimiter,
      setTabs: ctx.setTabs,
      activeTabId: ctx.activeTabId,
      saveCurrentTabData: ctx.saveCurrentTabData,
    },
    tabLifecycleArgs: {
      activeTabId: ctx.activeTabId,
      tabs: ctx.tabs,
      tabDataMap: ctx.tabDataMap,
      patches: ctx.patches,
      rowOps: ctx.rowOps,
      columnOps: ctx.columnOps,
      textDirty: ctx.textDirty,
      loadTabData: ctx.loadTabData,
      saveCurrentTabData: ctx.saveCurrentTabData,
      resetTextSession: ctx.resetTextSession,
      setTabs: ctx.setTabs,
      setActiveTabId: ctx.setActiveTabId,
      setFileMode: ctx.setFileMode,
      setRows: ctx.setRows,
      setHeaders: ctx.setHeaders,
      setPatches: ctx.setPatches,
      setRowIndexMap: ctx.setRowIndexMap,
      setTabDataMap: ctx.setTabDataMap,
      t: ctx.t,
    },
    fileOpenArgs: {
      activeTabId: ctx.activeTabId,
      tabs: ctx.tabs,
      saveCurrentTabData: ctx.saveCurrentTabData,
      importFirstRowHeader: ctx.importFirstRowHeader,
      importSkipRows: ctx.importSkipRows,
      pendingImportRef: ctx.pendingImportRef,
      pendingInitialSaveRef: ctx.pendingInitialSaveRef,
      resetTextSession: ctx.resetTextSession,
      closeSession: ctx.closeSession,
      openCsvPath: ctx.openCsvPath,
      openText: ctx.openText,
      setFileMode: ctx.setFileMode,
      resetSessionState: ctx.resetSessionState,
      requestWindow: ctx.requestWindow,
      setFileSizeBytes: ctx.setFileSizeBytes,
      shouldAutoBuildIndex: ctx.shouldAutoBuildIndex,
      refreshTotalRows: ctx.refreshTotalRows,
      loadDraftForPath: ctx.loadDraftForPath,
      clearDraftForPath: ctx.clearDraftForPath,
      setPatches: ctx.setPatches,
      setClearedRows: ctx.setClearedRows,
      setClearedCols: ctx.setClearedCols,
      setUndoStack: ctx.setUndoStack,
      setRedoStack: ctx.setRedoStack,
      addRecentFile: ctx.addRecentFile,
      t: ctx.t,
    },
  };
}
