import type useTabDataPersistence from "./useTabDataPersistence";

type BuildTabDataPersistenceOptionsContext = Record<string, any>;

export default function buildTabDataPersistenceOptions(
  ctx: BuildTabDataPersistenceOptionsContext,
): Parameters<typeof useTabDataPersistence>[0] {
  return {
    tabDataMap: ctx.tabDataMap,
    setTabDataMap: ctx.setTabDataMap,
    rows: ctx.rows,
    headers: ctx.headers,
    delimiter: ctx.delimiter,
    delimiterApplied: ctx.delimiterApplied,
    windowStart: ctx.windowStart,
    windowSize: ctx.windowSize,
    eof: ctx.eof,
    patches: ctx.patches,
    undoStack: ctx.undoStack,
    redoStack: ctx.redoStack,
    columnWidths: ctx.columnWidths,
    rowHeaderWidth: ctx.rowHeaderWidth,
    rowHeight: ctx.rowHeight,
    headerHeightOverride: ctx.headerHeightOverride,
    rowHeightOverrides: ctx.rowHeightOverrides,
    autoFitColumns: ctx.autoFitColumns,
    hiddenCols: ctx.hiddenCols,
    totalRows: ctx.totalRows,
    preview: ctx.preview,
    activePath: ctx.activePath,
    rowOps: ctx.rowOps,
    columnOps: ctx.columnOps,
    clearedRows: ctx.clearedRows,
    clearedCols: ctx.clearedCols,
    columnOrder: ctx.columnOrder,
    textContent: ctx.textContent,
    textDirty: ctx.textDirty,
    textPath: ctx.textPath,
    textEncoding: ctx.textEncoding,
    textReadOnlyPreview: ctx.textReadOnlyPreview,
    textPreviewOffset: ctx.textPreviewOffset,
    textPreviewHasPrev: ctx.textPreviewHasPrev,
    textPreviewHasNext: ctx.textPreviewHasNext,
    textPreviewBytes: ctx.textPreviewBytes,
    textTotalBytes: ctx.textTotalBytes,
    textPreviewReplaceOffset: ctx.textPreviewReplaceOffset,
    textPreviewReplaceBytes: ctx.textPreviewReplaceBytes,
    setFileMode: ctx.setFileMode,
    setDelimiter: ctx.setDelimiter,
    setPatches: ctx.setPatches,
    setUndoStack: ctx.setUndoStack,
    setRedoStack: ctx.setRedoStack,
    setRowOps: ctx.setRowOps,
    setColumnOps: ctx.setColumnOps,
    setClearedRows: ctx.setClearedRows,
    setClearedCols: ctx.setClearedCols,
    setHiddenCols: ctx.setHiddenCols,
    setColumnOrder: ctx.setColumnOrder,
    setColumnWidths: ctx.setColumnWidths,
    setRowHeaderWidth: ctx.setRowHeaderWidth,
    setRowHeight: ctx.setRowHeight,
    setHeaderHeightOverride: ctx.setHeaderHeightOverride,
    setRowHeightOverrides: ctx.setRowHeightOverrides,
    setAutoFitColumns: ctx.setAutoFitColumns,
    setTotalRows: ctx.setTotalRows,
    setRows: ctx.setRows,
    setHeaders: ctx.setHeaders,
    setWindowStart: ctx.setWindowStart,
    setWindowSize: ctx.setWindowSize,
    setEof: ctx.setEof,
    closeSession: ctx.closeSession,
    openCsvPath: ctx.openCsvPath,
    requestWindow: ctx.requestWindow,
    resetWindowCaches: ctx.resetWindowCaches,
    setTextPath: ctx.setTextPath,
    setTextContentState: ctx.setTextContentState,
    setTextDirty: ctx.setTextDirty,
    setTextEncoding: ctx.setTextEncoding,
    setTextReadOnlyPreview: ctx.setTextReadOnlyPreview,
    setTextPreviewOffset: ctx.setTextPreviewOffset,
    setTextPreviewHasPrev: ctx.setTextPreviewHasPrev,
    setTextPreviewHasNext: ctx.setTextPreviewHasNext,
    setTextPreviewBytes: ctx.setTextPreviewBytes,
    setTextTotalBytes: ctx.setTextTotalBytes,
    setTextPreviewReplaceOffset: ctx.setTextPreviewReplaceOffset,
    setTextPreviewReplaceBytes: ctx.setTextPreviewReplaceBytes,
  };
}
