import useAppCommandActions from "./useAppCommandActions";

type UseAppCommandActionsBridgeContext = Record<string, any>;

export default function useAppCommandActionsBridge(ctx: UseAppCommandActionsBridgeContext) {
  const {
    csvInputState,
    tabState,
    csvSessionState,
    textSessionState,
    csvDataModelState,
    csvDataLoaderState,
    csvWorkflowActions,
    fileOpsState,
    pendingImportRef,
    pendingInitialSaveRef,
    loadDraftForPath,
    loadTabData,
    saveCurrentTabData,
    clearDraftForPath,
    addRecentFile,
    setFileMode,
    shouldAutoBuildIndex,
    t,
    locale,
    setShowExportPanel,
    setShowFindBar,
    setShowFindPanel,
    setShowMacroPanel,
    setShowOpsPanel,
    setShowQuickbar,
    setShowStatsPanel,
  } = ctx;

  return useAppCommandActions({
    csvInputState,
    activeTabId: tabState.activeTabId,
    addRecentFile,
    clearDraftForPath,
    closeSession: csvSessionState.closeSession,
    columnOps: csvDataModelState.columnOps,
    delimiter: csvSessionState.delimiter,
    delimiterApplied: csvSessionState.delimiterApplied,
    fileMode: ctx.fileMode,
    importFirstRowHeader: csvInputState.importFirstRowHeader,
    importSkipRows: csvInputState.importSkipRows,
    loadDraftForPath,
    loadTabData,
    openCsvPath: csvSessionState.openCsvPath,
    openText: textSessionState.openText,
    patches: csvDataModelState.patches,
    pendingImportRef,
    pendingInitialSaveRef,
    preview: csvSessionState.preview,
    refreshTotalRows: csvDataLoaderState.refreshTotalRows,
    requestWindow: csvDataLoaderState.requestWindow,
    resetFileOps: fileOpsState.resetFileOps,
    resetOps: csvDataModelState.resetOps,
    resetSessionState: ctx.resetSessionState,
    resetTextSession: textSessionState.resetTextSession,
    rowOps: csvDataModelState.rowOps,
    saveCurrentTabData,
    saveTextAs: ctx.saveTextAs,
    saveTextTo: textSessionState.saveTextTo,
    saveToPath: fileOpsState.saveToPath,
    setActiveTabId: tabState.setActiveTabId,
    setClearedCols: csvDataModelState.setClearedCols,
    setClearedRows: csvDataModelState.setClearedRows,
    setEditingCell: csvDataModelState.setEditingCell,
    setFileMode,
    setFileSizeBytes: csvDataLoaderState.setFileSizeBytes,
    setHeaders: csvSessionState.setHeaders,
    setPatches: csvDataModelState.setPatches,
    setRedoStack: csvDataModelState.setRedoStack,
    setRowIndexMap: ctx.setRowIndexMap,
    setRows: csvSessionState.setRows,
    setTabDataMap: tabState.setTabDataMap,
    setTabs: tabState.setTabs,
    setUndoStack: csvDataModelState.setUndoStack,
    shouldAutoBuildIndex,
    t,
    tabDataMap: tabState.tabDataMap,
    tabs: tabState.tabs,
    textDirty: textSessionState.textDirty,
    textPath: textSessionState.textPath,
    windowStart: csvDataLoaderState.windowStart,
    applyFindReplace: fileOpsState.applyFindReplace,
    clearEdits: csvWorkflowActions.clearEdits,
    loadNextWindow: ctx.loadNextWindow,
    locale,
    redo: csvDataModelState.redo,
    runFindReplaceOnFile: fileOpsState.runFindReplaceOnFile,
    runFullStats: fileOpsState.runFullStats,
    runMacro: fileOpsState.runMacro,
    runMacroOnFile: fileOpsState.runMacroOnFile,
    saveAsCurrent: csvWorkflowActions.saveAsCurrent,
    setShowExportPanel,
    setShowFindBar,
    setShowFindPanel,
    setShowMacroPanel,
    setShowOpsPanel,
    setShowQuickbar,
    setShowStatsPanel,
    undo: csvDataModelState.undo,
  });
}
