import buildTabDataPersistenceOptions from "./buildTabDataPersistenceOptions";
import useTabDataPersistence from "./useTabDataPersistence";

type UseAppTabPersistenceBridgeContext = Record<string, any>;

export default function useAppTabPersistenceBridge(ctx: UseAppTabPersistenceBridgeContext) {
  const { tabState, csvSessionState, textSessionState, gridLayoutState, columnManagementState, csvDataModelState, csvDataLoaderState, setFileMode } = ctx;

  return useTabDataPersistence(buildTabDataPersistenceOptions({
    tabDataMap: tabState.tabDataMap,
    setTabDataMap: tabState.setTabDataMap,
    rows: csvSessionState.rows,
    headers: csvSessionState.headers,
    delimiter: csvSessionState.delimiter,
    delimiterApplied: csvSessionState.delimiterApplied,
    windowStart: csvDataLoaderState.windowStart,
    windowSize: csvDataLoaderState.windowSize,
    eof: csvSessionState.eof,
    patches: csvDataModelState.patches,
    undoStack: csvDataModelState.undoStack,
    redoStack: csvDataModelState.redoStack,
    columnWidths: gridLayoutState.columnWidths,
    rowHeaderWidth: gridLayoutState.rowHeaderWidth,
    rowHeight: gridLayoutState.rowHeight,
    headerHeightOverride: gridLayoutState.headerHeightOverride,
    rowHeightOverrides: gridLayoutState.rowHeightOverrides,
    autoFitColumns: gridLayoutState.autoFitColumns,
    hiddenCols: columnManagementState.hiddenCols,
    totalRows: csvDataLoaderState.totalRows,
    preview: csvSessionState.preview,
    activePath: csvSessionState.activePath,
    rowOps: csvDataModelState.rowOps,
    columnOps: csvDataModelState.columnOps,
    clearedRows: csvDataModelState.clearedRows,
    clearedCols: csvDataModelState.clearedCols,
    columnOrder: columnManagementState.columnOrder,
    textContent: textSessionState.textContent,
    textDirty: textSessionState.textDirty,
    textPath: textSessionState.textPath,
    textEncoding: textSessionState.textEncoding,
    textReadOnlyPreview: textSessionState.textReadOnlyPreview,
    textPreviewOffset: textSessionState.textPreviewOffset,
    textPreviewHasPrev: textSessionState.textPreviewHasPrev,
    textPreviewHasNext: textSessionState.textPreviewHasNext,
    textPreviewBytes: textSessionState.textPreviewBytes,
    textTotalBytes: textSessionState.textTotalBytes,
    textPreviewReplaceOffset: textSessionState.textPreviewReplaceOffset,
    textPreviewReplaceBytes: textSessionState.textPreviewReplaceBytes,
    setFileMode,
    setDelimiter: csvSessionState.setDelimiter,
    setPatches: csvDataModelState.setPatches,
    setUndoStack: csvDataModelState.setUndoStack,
    setRedoStack: csvDataModelState.setRedoStack,
    setRowOps: csvDataModelState.setRowOps,
    setColumnOps: csvDataModelState.setColumnOps,
    setClearedRows: csvDataModelState.setClearedRows,
    setClearedCols: csvDataModelState.setClearedCols,
    setHiddenCols: columnManagementState.setHiddenCols,
    setColumnOrder: columnManagementState.setColumnOrder,
    setColumnWidths: gridLayoutState.setColumnWidths,
    setRowHeaderWidth: gridLayoutState.setRowHeaderWidth,
    setRowHeight: gridLayoutState.setRowHeight,
    setHeaderHeightOverride: gridLayoutState.setHeaderHeightOverride,
    setRowHeightOverrides: gridLayoutState.setRowHeightOverrides,
    setAutoFitColumns: gridLayoutState.setAutoFitColumns,
    setTotalRows: csvDataLoaderState.setTotalRows,
    setRows: csvSessionState.setRows,
    setHeaders: csvSessionState.setHeaders,
    setWindowStart: csvDataLoaderState.setWindowStart,
    setWindowSize: csvDataLoaderState.setWindowSize,
    setEof: csvSessionState.setEof,
    closeSession: csvSessionState.closeSession,
    openCsvPath: csvSessionState.openCsvPath,
    requestWindow: csvDataLoaderState.requestWindow,
    resetWindowCaches: csvDataLoaderState.resetWindowCaches,
    setTextPath: textSessionState.setTextPath,
    setTextContentState: textSessionState.setTextContentState,
    setTextDirty: textSessionState.setTextDirty,
    setTextEncoding: textSessionState.setTextEncoding,
    setTextReadOnlyPreview: textSessionState.setTextReadOnlyPreview,
    setTextPreviewOffset: textSessionState.setTextPreviewOffset,
    setTextPreviewHasPrev: textSessionState.setTextPreviewHasPrev,
    setTextPreviewHasNext: textSessionState.setTextPreviewHasNext,
    setTextPreviewBytes: textSessionState.setTextPreviewBytes,
    setTextTotalBytes: textSessionState.setTextTotalBytes,
    setTextPreviewReplaceOffset: textSessionState.setTextPreviewReplaceOffset,
    setTextPreviewReplaceBytes: textSessionState.setTextPreviewReplaceBytes,
  }));
}
