import useCsvWorkflowActions from "./useCsvWorkflowActions";

type UseCsvWorkflowActionsBridgeContext = Record<string, any>;

export default function useCsvWorkflowActionsBridge(ctx: UseCsvWorkflowActionsBridgeContext) {
  return useCsvWorkflowActions({
    csvInputState: ctx.csvInputState,
    csvSortFilterModel: ctx.csvSortFilterModel,
    csvFindState: ctx.csvFindState,
    fileOpsState: ctx.fileOpsState,
    fileMode: ctx.fileMode,
    saveTextAs: ctx.textSearchActions.saveTextAs,
    clearDraftForPath: ctx.clearDraftForPath,
    preview: ctx.csvSessionState.preview,
    updateActiveTabPath: ctx.updateActiveTabPath,
    resetSessionState: ctx.resetSessionState,
    closeSession: ctx.csvSessionState.closeSession,
    openCsvPath: ctx.csvSessionState.openCsvPath,
    setFileMode: ctx.setFileMode,
    requestWindow: ctx.csvDataLoaderState.requestWindow,
    setFileSizeBytes: ctx.csvDataLoaderState.setFileSizeBytes,
    shouldAutoBuildIndex: ctx.shouldAutoBuildIndex,
    refreshTotalRows: ctx.csvDataLoaderState.refreshTotalRows,
    activeTabId: ctx.tabState.activeTabId,
    saveCurrentTabData: ctx.saveCurrentTabData,
    applyDelimiter: ctx.csvSessionState.applyDelimiter,
    fileSizeBytes: ctx.csvDataLoaderState.fileSizeBytes,
    pendingInitialSaveRef: ctx.pendingInitialSaveRef,
    loading: ctx.csvSessionState.loading,
    textLoading: ctx.textSessionState.textLoading,
    clearModelEdits: ctx.csvDataModelState.clearEdits,
    setError: ctx.setError,
    setGlobalViewPatchTick: ctx.setGlobalViewPatchTick,
    setIsDraggingSelection: ctx.setIsDraggingSelection,
    updateSelection: ctx.updateSelection,
    windowStart: ctx.csvDataLoaderState.windowStart,
    rows: ctx.csvSessionState.rows,
    rowVirtualizer: ctx.csvViewOrchestration.rowVirtualizer,
    t: ctx.t,
    globalViewIdRef: ctx.globalViewIdRef,
    effectiveTotalRows: ctx.csvViewOrchestration.effectiveTotalRows,
    windowSize: ctx.csvDataLoaderState.windowSize,
    requestIdRef: ctx.csvDataLoaderState.requestIdRef,
    loadWindow: ctx.csvDataLoaderState.loadWindow,
    selectionColumnCount: ctx.selectionColumnCount,
    getCellValue: ctx.csvDataModelState.getCellValue,
    getActiveRange: ctx.getActiveRange,
    headers: ctx.csvSessionState.headers,
    insertRow: ctx.csvDataModelState.insertRow,
    insertRowWithUndo: ctx.csvDataModelState.insertRowWithUndo,
    deleteRow: ctx.csvDataModelState.deleteRow,
    deleteRowWithUndo: ctx.csvDataModelState.deleteRowWithUndo,
    insertColumn: ctx.csvDataModelState.insertColumn,
    insertColumnWithUndo: ctx.csvDataModelState.insertColumnWithUndo,
    deleteColumn: ctx.csvDataModelState.deleteColumn,
    deleteColumnWithUndo: ctx.csvDataModelState.deleteColumnWithUndo,
    renameColumn: ctx.csvDataModelState.renameColumn,
    renameColumnWithUndo: ctx.csvDataModelState.renameColumnWithUndo,
    globalViewLoading: ctx.globalViewLoading,
    insertRowAtIndex: ctx.csvDataModelState.insertRowAtIndex,
    duplicateColumnAtIndex: ctx.csvDataModelState.duplicateColumnAtIndex,
    startHeaderEditing: ctx.startHeaderEditing,
    shiftClearedRowsOnInsert: ctx.csvDataModelState.shiftClearedRowsOnInsert,
    shiftClearedColsOnInsert: ctx.csvDataModelState.shiftClearedColsOnInsert,
    dataColumnCount: ctx.dataColumnCount,
    setClearedRows: ctx.csvDataModelState.setClearedRows,
    setClearedCols: ctx.csvDataModelState.setClearedCols,
    setPatches: ctx.csvDataModelState.setPatches,
    appendContextUndo: ctx.appendContextUndo,
    resetRedoStack: ctx.resetRedoStack,
  });
}
