import { TEXT_FIND_RESULTS_PANEL_LIMIT } from "../utils/textFind";
import useTextSearchReplaceActions from "./useTextSearchReplaceActions";

type UseTextSearchActionsBridgeContext = Record<string, any>;

export default function useTextSearchActionsBridge(ctx: UseTextSearchActionsBridgeContext) {
  return useTextSearchReplaceActions({
    textPath: ctx.textSessionState.textPath,
    saveTextTo: ctx.textSessionState.saveTextTo,
    updateActiveTabPath: ctx.updateActiveTabPath,
    textReadOnlyPreview: ctx.textSessionState.textReadOnlyPreview,
    textTotalBytes: ctx.textSessionState.textTotalBytes,
    textChunkJumpInput: ctx.textFindReplaceState.textChunkJumpInput,
    setTextChunkJumpInput: ctx.textFindReplaceState.setTextChunkJumpInput,
    loadTextPreviewChunkAtOffset: ctx.textSessionState.loadTextPreviewChunkAtOffset,
    setError: ctx.setError,
    t: ctx.t,
    resetTextFindResultsModel: ctx.textFindResultsModelState.resetTextFindResultsModel,
    setTextFindRunning: ctx.textFindReplaceState.setTextFindRunning,
    setTextFindJobId: ctx.textFindReplaceState.setTextFindJobId,
    setTextFindProgress: ctx.textFindReplaceState.setTextFindProgress,
    setTextFindHits: ctx.textFindReplaceState.setTextFindHits,
    setTextFindResultPanelStart: ctx.textFindResultPanelPagination.setTextFindResultPanelStart,
    setTextFindResultPanelPageSpan: ctx.textFindResultPanelPagination.setTextFindResultPanelPageSpan,
    setActiveTextFindIndex: ctx.textFindReplaceState.setActiveTextFindIndex,
    setTextFindHasMore: ctx.textFindReplaceState.setTextFindHasMore,
    setTextFindMatchedCount: ctx.textFindReplaceState.setTextFindMatchedCount,
    setTextFindScannedBytes: ctx.textFindReplaceState.setTextFindScannedBytes,
    setTextFindElapsedMs: ctx.textFindReplaceState.setTextFindElapsedMs,
    setTextReplaceRunning: ctx.textFindReplaceState.setTextReplaceRunning,
    setTextReplaceJobId: ctx.textFindReplaceState.setTextReplaceJobId,
    setTextReplaceProgress: ctx.textFindReplaceState.setTextReplaceProgress,
    setTextReplaceAppliedCount: ctx.textFindReplaceState.setTextReplaceAppliedCount,
    setTextReplaceScannedBytes: ctx.textFindReplaceState.setTextReplaceScannedBytes,
    setTextReplaceElapsedMs: ctx.textFindReplaceState.setTextReplaceElapsedMs,
    textEncoding: ctx.textSessionState.textEncoding,
    textFindQuery: ctx.textFindReplaceState.textFindQuery,
    textFindUseRegex: ctx.textFindReplaceState.textFindUseRegex,
    textFindMatchCase: ctx.textFindReplaceState.textFindMatchCase,
    textFindRunning: ctx.textFindReplaceState.textFindRunning,
    textFindJobId: ctx.textFindReplaceState.textFindJobId,
    textReplaceValue: ctx.textFindReplaceState.textReplaceValue,
    textReplacePreserveCase: ctx.textFindReplaceState.textReplacePreserveCase,
    textReplaceConfirmEach: ctx.textFindReplaceState.textReplaceConfirmEach,
    textReplaceRunning: ctx.textFindReplaceState.textReplaceRunning,
    textReplaceJobId: ctx.textFindReplaceState.textReplaceJobId,
    textDirty: ctx.textSessionState.textDirty,
    textPreviewOffset: ctx.textSessionState.textPreviewOffset,
    setTextReplaceValue: ctx.textFindReplaceState.setTextReplaceValue,
    textContent: ctx.textSessionState.textContent,
    textAreaRef: ctx.textFindReplaceState.textAreaRef,
    setTextContent: ctx.textSessionState.setTextContent,
    textFindHits: ctx.textFindReplaceState.textFindHits,
    textFindHitJumpInput: ctx.textFindReplaceState.textFindHitJumpInput,
    setTextFindHitJumpInput: ctx.textFindReplaceState.setTextFindHitJumpInput,
    textFindOffsetJumpInput: ctx.textFindReplaceState.textFindOffsetJumpInput,
    textFindResultPanelRange: ctx.textFindResultPanelPagination.textFindResultPanelRange,
    textFindResultPanelCanLoadMore: ctx.textFindResultPanelPagination.textFindResultPanelCanLoadMore,
    textFindHasMoreRenderedGroups: ctx.textFindResultsModelState.textFindHasMoreRenderedGroups,
    loadMoreTextFindRenderedGroups: ctx.textFindResultsModelState.loadMoreTextFindRenderedGroups,
    activeTextFindIndex: ctx.textFindReplaceState.activeTextFindIndex,
    textFindResultsPanelLimit: TEXT_FIND_RESULTS_PANEL_LIMIT,
  });
}
