export type CsvModeStatusBarProps = {
  t: (en: string, zh: string) => string;
  loading: boolean;
  windowLoading: boolean;
  fileMode: "none" | "csv" | "text";
  csvGridFocused: boolean;
  csvEditing: boolean;
  selectionMode: "cell" | "row" | "col";
  previewPath: string | null;
  eof: boolean;
  rowsLength: number;
  patchCount: number;
  macroAppliedCount: number;
  findAppliedCount: number;
  opStatus: string | null;
  indexRunning: boolean;
  indexProgress: number;
  indexCanceled: boolean;
  findRunning: boolean;
  findProgress: number;
  findCanceled: boolean;
  findMatchedCount: number | null;
  findScannedRows: number | null;
  findElapsedMs: number | null;
  globalViewLoading: boolean;
  autoIndexMode: "large_only" | "all";
  forceExternalSort: boolean;
  lastIndexTrigger: "auto" | "manual" | null;
  totalRows: number | null;
  delimiter: string;
  delimiterApplied: string | null;
  refreshTotalRows: (path: string, delimiter: string, trigger?: "auto" | "manual") => Promise<void>;
  cancelIndexBuild: () => void;
  cancelFindMatchJob: () => void;
};
